### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by darkwolf999** [denisskin/todoapp#2]
Дай пожалуйста ссылку на apk

**Comment by denisskin** [comment]
https://github.com/denisskin/todoapp/raw/master/dist/app-release.apk

**Comment by darkwolf999** [comment]
## Чистота кода и общая структура проекта (4/5)
Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов **(0.5/1)**
Добавлен и работает flutter_lints, в коде нет необоснованных игноров правил **(0.5/1)**
- Линтер не был настроен

Форматирование кода присутствует **(1/1)**
Код разбит на фичи и слои **(2/2)**

## State-Management (8/8)
Для стейт-менеджмента используется любое решение  **(5/5)**
Консистентность данных при редактировании на разных экранах: изменил на одном экране, проросло на другой мгновенно без плясок с открытием чего-либо туда-сюда **(3/3)**

## Получение и хранение данных (4.5/10)
Реализована работа с бэкендом, данные отправляются/получаются с сервера **(1.5/3)**
- На обновление одной таски надо использовать метод PUT, а не PATCH

Работа с сетью выделена в отдельный слой, код инкапсулирован. Отсутствует логика в слое представления **(2/2)**
Организовано сохранение данных на диск при помощи одной из представленных библиотек **(0/3)**
- SharedPreferences не подходит в качестве хранилища таких данных. Оно скорее для настроек приложения/хранения единичных значений. Для БД лучше использовать, например, sqflite, либо Isar

Работа выделена в отдельный слой **(1/2)**
- В методе _initData() идет пересечение со слоем бэка


## Разное (1/3)
Работа с асинхронным кодом реализована однородно: нет бессвязной мешанины из .then и async/await, подход выбран логично **(1/1)**
Интернационализация: используется пакет intl или аналогичный, строки изолированы и не захардкожены **(0/2)**

**Итого 17.5/26**
